server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/project_db
#    username: postgres
#    password: postgres
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: app_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # update: ????????????? ???????/????????? ??????? ??? ??????? ??????????
      ddl-auto: update
    show-sql: true # ?????????? SQL-??????? ? ???????
    properties:
      hibernate:
        # ??????? ??? ?????????? ?????? ? ????????????? Postgres
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # ?????? SQL ? ????? ???????? ? ????????